name: Download IPA

on:
  workflow_dispatch:
    inputs:
      app_name:
        description: "App name"
        default: "com.touchingapp.potatsolite"
        required: true
        type: string
      app_country:
        description: "App store country"
        default: "US"
        required: true
        type: string
      apple_email:
        description: "Apple ID Email"
        default: "example@gmail.com"
        required: true
        type: string
      apple_password:
        description: "Apple ID Password"
        default: "password"
        required: true
        type: string

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.x
      uses: actions/setup-python@v3
      with:
        python-version: "3.x"
    - name: Install dependencies
      working-directory: ipaoutput
      run: |
        python3 -m pip install --upgrade pip
        sudo apt-get install python3-setuptools
        pip install flake8
        pip install requests
        pip install rich
        if [ -f requirements.txt ]; then pip3 install -r requirements.txt; fi
    - name: Download IPA
      run: |
        python3 main.py lookup -b "${{ env.APP_NAME }}" -c "${{ env.APP_COUNTRY }}" download --purchase -e "${{ env.APPLE_EMAIL }}" -p "${{ env.APPLE_PASSWORD }}" -o ipaoutput
        
      env:
          APP_NAME: ${{ inputs.app_name }}
          APP_COUNTRY: ${{ inputs.app_country}}
          APPLE_EMAIL: ${{ inputs.apple_email }}
          APPLE_PASSWORD: ${{ inputs.apple_password }}
          
      # Runs a single command using the runners shell
    - name: Archive IPA download
      uses: actions/upload-artifact@v3
      with:
          name: Archive IPA download
          path: |
            ipaoutput
            !ipaoutput/**/*.md
